---
name: Puppeteer
version: dev
slug: nodejs-puppeteer
description: Docker NodeJS base images used by Home Assistant Community Add-ons.
url: https://github.com/Subzerox64/addon-base-nodejs/
arch:
  - aarch64
  - amd64
  - armv7
